export enum profileTypes {
  FETCH_GET_PROFILE = 'FETCH_GET_PROFILE',
  FETCH_GET_PROFILE_REQUEST = 'FETCH_GET_PROFILE_REQUEST',
  FETCH_GET_PROFILE_SUCCESS = 'FETCH_GET_PROFILE_SUCCESS',
  FETCH_GET_PROFILE_FAILURE = 'FETCH_GET_PROFILE_FAILURE',
}
