export enum authorsTypes {
  FETCH_GET_AUTHORS = 'FETCH_GET_AUTHORS',
  FETCH_GET_AUTHORS_REQUEST = 'FETCH_GET_AUTHORS_REQUEST',
  FETCH_GET_AUTHORS_SUCCESS = 'FETCH_GET_AUTHORS_SUCCESS',
  FETCH_GET_AUTHORS_FAILURE = 'FETCH_GET_AUTHORS_FAILURE',
}
