export enum authTypes {
  FETCH_GENERATE_TOKEN = 'FETCH_GENERATE_TOKEN',
  FETCH_GENERATE_TOKEN_REQUEST = 'FETCH_GENERATE_TOKEN_REQUEST',
  FETCH_GENERATE_TOKEN_SUCCESS = 'FETCH_GENERATE_TOKEN_SUCCESS',
  FETCH_GENERATE_TOKEN_FAILURE = 'FETCH_GENERATE_TOKEN_FAILURE',
}
