export enum tagsTypes {
  FETCH_GET_TAGS = 'FETCH_GET_TAGS',
  FETCH_GET_TAGS_REQUEST = 'FETCH_GET_TAGS_REQUEST',
  FETCH_GET_TAGS_SUCCESS = 'FETCH_GET_TAGS_SUCCESS',
  FETCH_GET_TAGS_FAILURE = 'FETCH_GET_TAGS_FAILURE',
}
